eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka:khTUcUUQ33WkJGC@localhost:8761/eureka}
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
