pit:
  security.jwt:
    key: 7387acd61b2666c94f2f6646b6d53f6359ace919
    cookie.secure: false

backend:
  db:
    scheme: jdbc:oracle:thin:@
    server: mnbdqa001-scan.naiss.local
    port: 1521
    database: PDBQASIG
    username: OWN_SIGTE
    password: wqe2jtWS
    show-sql: false
    driver-class-name: oracle.jdbc.OracleDriver
    opts:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.Oracle12cDialect
