spring:
  data:
    cassandra:
      contact-points: 35.237.201.162
      port: 9042
      cluster-name: cluster-gcp
      keyspace-name: CORE
      password: cassandra
      username: cassandra
      consistency-level: ONE
      connect-timeout-millis: 60000

eureka:
  instance:
    metadata-map:
      management:
        port: 9090
