backend:
  db:
    scheme: jdbc:oracle:thin:@
    server: mnbdqa001-scan.naiss.local
    port: 1521
    database: PDBQASIG_PREPROD
    username: OWN_SIGTE
    password: x2QcE9QR
    show-sql: false
    driver-class-name: oracle.jdbc.OracleDriver
    opts:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.Oracle12cDialect
 
minsal:
  sigte:
    api-gee:
      obtener-prestadores: http://apiintranet.naiss.local:9003/v1/prestadores/institucionales
      obtener-contacto-prestadores: http://apiintranet.naiss.local:9003/v1/prestadores/contactos/institucionales

spring:
  datasource:
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 500

eureka:
  instance:
    metadata-map:
      management:
        port: 9090
