spring:
  data:
    mongodb:
      #host: 172.18.0.81
      host: localhost
      port: 27017
      database: repo_cert
     
cert:
  path: C:\\certificate.pfx
  pass: server

eureka:
  instance:
    metadata-map:
      management:
        port: 9090
