spring:
  data:
    mongodb:
      host: 35.243.165.70
      port: 27017
      database: repo_cert
     
cert:
  path: C:\\certificate.pfx
  pass: server

eureka:
  instance:
    metadata-map:
      management:
        port: 9090
